const database = [
    // ==========================================
    // PHYSICS (100 Formulas)
    // ==========================================
    {title: "Average Speed", tags: "Physics > Kinematics", text: "v_avg = Total Distance / Total Time"},
    {title: "Average Velocity", tags: "Physics > Kinematics", text: "v_avg = Δx / Δt"},
    {title: "Instantaneous Velocity", tags: "Physics > Kinematics", text: "v = dx/dt"},
    {title: "Instantaneous Acceleration", tags: "Physics > Kinematics", text: "a = dv/dt = d²x/dt²"},
    {title: "Kinematic Eq 1", tags: "Physics > Kinematics", text: "v = u + at"},
    {title: "Kinematic Eq 2", tags: "Physics > Kinematics", text: "s = ut + ½at²"},
    {title: "Kinematic Eq 3", tags: "Physics > Kinematics", text: "v² = u² + 2as"},
    {title: "Displacement in nth second", tags: "Physics > Kinematics", text: "S_n = u + ½a(2n - 1)"},
    {title: "Relative Velocity", tags: "Physics > Kinematics", text: "v_AB = v_A - v_B"},
    {title: "Projectile Time of Flight", tags: "Physics > Kinematics", text: "T = 2u·sinθ / g"},
    {title: "Projectile Max Height", tags: "Physics > Kinematics", text: "H = u²·sin²θ / 2g"},
    {title: "Projectile Horizontal Range", tags: "Physics > Kinematics", text: "R = u²·sin(2θ) / g"},
    {title: "Equation of Trajectory", tags: "Physics > Kinematics", text: "y = x·tanθ - (gx²) / (2u²·cos²θ)"},
    {title: "Angular Velocity", tags: "Physics > Circular Motion", text: "ω = dθ/dt = v/r"},
    {title: "Centripetal Acceleration", tags: "Physics > Circular Motion", text: "a_c = v² / r = ω²r"},
    {title: "Newton's 2nd Law", tags: "Physics > NLM", text: "F = dp/dt = ma"},
    {title: "Impulse", tags: "Physics > NLM", text: "J = F·Δt = Δp"},
    {title: "Conservation of Momentum", tags: "Physics > NLM", text: "m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂"},
    {title: "Static Friction", tags: "Physics > Friction", text: "f_s ≤ μ_s·N"},
    {title: "Kinetic Friction", tags: "Physics > Friction", text: "f_k = μ_k·N"},
    {title: "Angle of Repose", tags: "Physics > Friction", text: "tan(α) = μ_s"},
    {title: "Work Done by Constant Force", tags: "Physics > WPE", text: "W = F·d·cosθ"},
    {title: "Work Done by Variable Force", tags: "Physics > WPE", text: "W = ∫ F dx"},
    {title: "Kinetic Energy", tags: "Physics > WPE", text: "K = ½mv² = p² / 2m"},
    {title: "Work-Energy Theorem", tags: "Physics > WPE", text: "W_net = ΔK"},
    {title: "Gravitational Potential Energy", tags: "Physics > WPE", text: "U = mgh"},
    {title: "Spring Potential Energy", tags: "Physics > WPE", text: "U = ½kx²"},
    {title: "Power", tags: "Physics > WPE", text: "P = dW/dt = F·v"},
    {title: "Center of Mass (Discrete)", tags: "Physics > COM", text: "X_cm = Σ(m_i·x_i) / Σm_i"},
    {title: "Center of Mass (Continuous)", tags: "Physics > COM", text: "X_cm = (1/M) ∫ x dm"},
    {title: "Coefficient of Restitution", tags: "Physics > Collisions", text: "e = (v₂ - v₁) / (u₁ - u₂)"},
    {title: "Torque", tags: "Physics > Rotational", text: "τ = r × F = Iα"},
    {title: "Angular Momentum", tags: "Physics > Rotational", text: "L = r × p = Iω"},
    {title: "Rotational Kinetic Energy", tags: "Physics > Rotational", text: "K_rot = ½Iω²"},
    {title: "Moment of Inertia (Ring/Cylinder)", tags: "Physics > Rotational", text: "I = MR²"},
    {title: "Moment of Inertia (Disc/Solid Cyl)", tags: "Physics > Rotational", text: "I = ½MR²"},
    {title: "Moment of Inertia (Solid Sphere)", tags: "Physics > Rotational", text: "I = (2/5)MR²"},
    {title: "Parallel Axis Theorem", tags: "Physics > Rotational", text: "I = I_cm + Md²"},
    {title: "Perpendicular Axis Theorem", tags: "Physics > Rotational", text: "I_z = I_x + I_y"},
    {title: "Rolling Kinetic Energy", tags: "Physics > Rotational", text: "K_total = ½mv² + ½Iω²"},
    {title: "Newton's Law of Gravitation", tags: "Physics > Gravitation", text: "F = G(m₁m₂) / r²"},
    {title: "Gravitational Field", tags: "Physics > Gravitation", text: "g = GM / r²"},
    {title: "Variation of g with Height", tags: "Physics > Gravitation", text: "g_h = g(1 - 2h/R)"},
    {title: "Variation of g with Depth", tags: "Physics > Gravitation", text: "g_d = g(1 - d/R)"},
    {title: "Gravitational Potential Energy", tags: "Physics > Gravitation", text: "U = -GMm / r"},
    {title: "Escape Velocity", tags: "Physics > Gravitation", text: "v_e = √(2GM / R)"},
    {title: "Orbital Velocity", tags: "Physics > Gravitation", text: "v_o = √(GM / r)"},
    {title: "Kepler's 3rd Law", tags: "Physics > Gravitation", text: "T² ∝ r³"},
    {title: "Hooke's Law", tags: "Physics > Solids", text: "Stress ∝ Strain"},
    {title: "Young's Modulus", tags: "Physics > Solids", text: "Y = (F/A) / (ΔL/L)"},
    {title: "Bulk Modulus", tags: "Physics > Solids", text: "B = -ΔP / (ΔV/V)"},
    {title: "Elastic Energy Density", tags: "Physics > Solids", text: "U = ½ × Stress × Strain"},
    {title: "Pressure at Depth", tags: "Physics > Fluids", text: "P = P₀ + ρgh"},
    {title: "Buoyant Force", tags: "Physics > Fluids", text: "F_B = ρ_fluid·V_sub·g"},
    {title: "Equation of Continuity", tags: "Physics > Fluids", text: "A₁v₁ = A₂v₂"},
    {title: "Bernoulli's Equation", tags: "Physics > Fluids", text: "P + ½ρv² + ρgh = Constant"},
    {title: "Terminal Velocity", tags: "Physics > Fluids", text: "v_t = 2r²(ρ - σ)g / 9η"},
    {title: "Surface Tension Energy", tags: "Physics > Fluids", text: "W = T·ΔA"},
    {title: "Linear Expansion", tags: "Physics > Thermal", text: "ΔL = L₀αΔT"},
    {title: "Heat Capacity", tags: "Physics > Thermal", text: "Q = mcΔT"},
    {title: "Latent Heat", tags: "Physics > Thermal", text: "Q = mL"},
    {title: "Stefan-Boltzmann Law", tags: "Physics > Thermal", text: "E = σT⁴"},
    {title: "Wien's Displacement Law", tags: "Physics > Thermal", text: "λ_max·T = b"},
    {title: "Ideal Gas Law", tags: "Physics > Thermodynamics", text: "PV = nRT"},
    {title: "First Law of Thermodynamics", tags: "Physics > Thermodynamics", text: "ΔQ = ΔU + ΔW"},
    {title: "Work in Isothermal", tags: "Physics > Thermodynamics", text: "W = nRT·ln(V₂/V₁)"},
    {title: "Work in Adiabatic", tags: "Physics > Thermodynamics", text: "W = (P₁V₁ - P₂V₂) / (γ - 1)"},
    {title: "Carnot Efficiency", tags: "Physics > Thermodynamics", text: "η = 1 - (T₂/T₁)"},
    {title: "SHM Equation", tags: "Physics > SHM", text: "a = -ω²x"},
    {title: "Time Period (Pendulum)", tags: "Physics > SHM", text: "T = 2π√(L/g)"},
    {title: "Time Period (Spring)", tags: "Physics > SHM", text: "T = 2π√(m/k)"},
    {title: "Velocity in SHM", tags: "Physics > SHM", text: "v = ω√(A² - x²)"},
    {title: "Wave Speed", tags: "Physics > Waves", text: "v = fλ"},
    {title: "Speed of Wave on String", tags: "Physics > Waves", text: "v = √(T/μ)"},
    {title: "Doppler Effect (Sound)", tags: "Physics > Waves", text: "f' = f(v ± v_o) / (v ∓ v_s)"},
    {title: "Coulomb's Law", tags: "Physics > Electrostatics", text: "F = k(q₁q₂) / r²"},
    {title: "Electric Field", tags: "Physics > Electrostatics", text: "E = kq / r²"},
    {title: "Electric Potential", tags: "Physics > Electrostatics", text: "V = kq / r"},
    {title: "Gauss's Law", tags: "Physics > Electrostatics", text: "∮ E·dA = q_in / ε₀"},
    {title: "Capacitance (Parallel Plate)", tags: "Physics > Capacitance", text: "C = ε₀A / d"},
    {title: "Energy in Capacitor", tags: "Physics > Capacitance", text: "U = ½CV² = Q² / 2C"},
    {title: "Ohm's Law", tags: "Physics > Current", text: "V = IR"},
    {title: "Resistance", tags: "Physics > Current", text: "R = ρL / A"},
    {title: "Drift Velocity", tags: "Physics > Current", text: "v_d = I / (neA)"},
    {title: "Electrical Power", tags: "Physics > Current", text: "P = VI = I²R = V²/R"},
    {title: "Kirchhoff's Voltage Law", tags: "Physics > Current", text: "ΣV = 0"},
    {title: "Biot-Savart Law", tags: "Physics > Magnetism", text: "dB = (μ₀I/4π) (dl×r)/r³"},
    {title: "Magnetic Field (Wire)", tags: "Physics > Magnetism", text: "B = μ₀I / 2πr"},
    {title: "Magnetic Force", tags: "Physics > Magnetism", text: "F = q(v × B)"},
    {title: "Force on Current Wire", tags: "Physics > Magnetism", text: "F = I(L × B)"},
    {title: "Magnetic Flux", tags: "Physics > EMI", text: "Φ_B = B·A·cosθ"},
    {title: "Faraday's Law", tags: "Physics > EMI", text: "ε = -N(dΦ/dt)"},
    {title: "Motional EMF", tags: "Physics > EMI", text: "ε = Bvl"},
    {title: "Energy in Inductor", tags: "Physics > EMI", text: "U = ½LI²"},
    {title: "RMS Current", tags: "Physics > AC", text: "I_rms = I₀ / √2"},
    {title: "Impedance (RLC)", tags: "Physics > AC", text: "Z = √[R² + (X_L - X_C)²]"},
    {title: "Mirror Formula", tags: "Physics > Optics", text: "1/f = 1/v + 1/u"},
    {title: "Lens Formula", tags: "Physics > Optics", text: "1/f = 1/v - 1/u"},
    {title: "Snell's Law", tags: "Physics > Optics", text: "n₁·sin(θ₁) = n₂·sin(θ₂)"},
    {title: "Photon Energy", tags: "Physics > Modern", text: "E = hf = hc / λ"},
    {title: "Einstein Photoelectric", tags: "Physics > Modern", text: "K_max = hf - Φ"},

    // ==========================================
    // CHEMISTRY (100 Formulas)
    // ==========================================
    {title: "Number of Moles", tags: "Chemistry > Physical", text: "n = Mass / Molar Mass"},
    {title: "Molarity (M)", tags: "Chemistry > Solutions", text: "M = Moles of Solute / V(L)"},
    {title: "Molality (m)", tags: "Chemistry > Solutions", text: "m = Moles of Solute / Mass of Solvent(kg)"},
    {title: "Mole Fraction (x)", tags: "Chemistry > Solutions", text: "x_A = n_A / (n_A + n_B)"},
    {title: "Normality (N)", tags: "Chemistry > Solutions", text: "N = Eq. Weight / V(L)"},
    {title: "Bohr Radius", tags: "Chemistry > Atomic", text: "r_n = 0.529 × (n²/Z) Å"},
    {title: "Velocity of Electron", tags: "Chemistry > Atomic", text: "v_n = 2.18 × 10⁶ × (Z/n) m/s"},
    {title: "Energy of Bohr Orbit", tags: "Chemistry > Atomic", text: "E_n = -13.6 × (Z²/n²) eV"},
    {title: "Rydberg Equation", tags: "Chemistry > Atomic", text: "1/λ = R_H·Z² [1/n₁² - 1/n₂²]"},
    {title: "De Broglie Wavelength", tags: "Chemistry > Atomic", text: "λ = h / mv = h / p"},
    {title: "Heisenberg Uncertainty", tags: "Chemistry > Atomic", text: "Δx·Δp ≥ h / 4π"},
    {title: "Ideal Gas Law", tags: "Chemistry > Gas", text: "PV = nRT"},
    {title: "Boyle's Law", tags: "Chemistry > Gas", text: "P₁V₁ = P₂V₂"},
    {title: "Charles's Law", tags: "Chemistry > Gas", text: "V₁/T₁ = V₂/T₂"},
    {title: "Graham's Law", tags: "Chemistry > Gas", text: "r₁/r₂ = √(M₂/M₁)"},
    {title: "RMS Velocity", tags: "Chemistry > Gas", text: "v_rms = √(3RT/M)"},
    {title: "Average Velocity", tags: "Chemistry > Gas", text: "v_avg = √(8RT/πM)"},
    {title: "Most Probable Velocity", tags: "Chemistry > Gas", text: "v_mp = √(2RT/M)"},
    {title: "Van der Waals Equation", tags: "Chemistry > Gas", text: "(P + an²/V²)(V - nb) = nRT"},
    {title: "Compressibility Factor", tags: "Chemistry > Gas", text: "Z = PV_real / nRT"},
    {title: "1st Law of Thermodynamics", tags: "Chemistry > Thermo", text: "ΔU = q + w"},
    {title: "Enthalpy Change", tags: "Chemistry > Thermo", text: "ΔH = ΔU + PΔV"},
    {title: "Heat Capacity at Const Vol", tags: "Chemistry > Thermo", text: "q_v = nC_vΔT = ΔU"},
    {title: "Heat Capacity at Const Pressure", tags: "Chemistry > Thermo", text: "q_p = nC_pΔT = ΔH"},
    {title: "Work in Rev Isothermal Expansion", tags: "Chemistry > Thermo", text: "w = -2.303 nRT log(V₂/V₁)"},
    {title: "Gibbs Free Energy", tags: "Chemistry > Thermo", text: "ΔG = ΔH - TΔS"},
    {title: "Spontaneity Condition", tags: "Chemistry > Thermo", text: "ΔG < 0"},
    {title: "Standard Free Energy", tags: "Chemistry > Thermo", text: "ΔG° = -2.303 RT log(K_eq)"},
    {title: "Equilibrium Constant (Kc)", tags: "Chemistry > Equilibrium", text: "Kc = [Products] / [Reactants]"},
    {title: "Kp and Kc Relation", tags: "Chemistry > Equilibrium", text: "Kp = Kc(RT)^Δn_g"},
    {title: "pH Definition", tags: "Chemistry > Equilibrium", text: "pH = -log[H⁺]"},
    {title: "Ionic Product of Water", tags: "Chemistry > Equilibrium", text: "Kw = [H⁺][OH⁻] = 10⁻¹⁴"},
    {title: "Henderson Equation (Acidic)", tags: "Chemistry > Equilibrium", text: "pH = pKa + log([Salt]/[Acid])"},
    {title: "Henderson Equation (Basic)", tags: "Chemistry > Equilibrium", text: "pOH = pKb + log([Salt]/[Base])"},
    {title: "Solubility Product", tags: "Chemistry > Equilibrium", text: "Ksp = [A⁺]ˣ[B⁻]ʸ"},
    {title: "Unit Cell Density", tags: "Chemistry > Solid", text: "d = (Z·M) / (N_A·a³)"},
    {title: "Bragg's Equation", tags: "Chemistry > Solid", text: "nλ = 2d·sinθ"},
    {title: "Packing Efficiency (SC)", tags: "Chemistry > Solid", text: "PE = 52.4%"},
    {title: "Packing Efficiency (BCC)", tags: "Chemistry > Solid", text: "PE = 68%"},
    {title: "Packing Efficiency (FCC)", tags: "Chemistry > Solid", text: "PE = 74%"},
    {title: "Raoult's Law", tags: "Chemistry > Solutions", text: "P_total = P_A°·x_A + P_B°·x_B"},
    {title: "Relative Lowering of Vapor Pressure", tags: "Chemistry > Solutions", text: "(P° - P_s)/P° = x_solute"},
    {title: "Elevation in Boiling Point", tags: "Chemistry > Solutions", text: "ΔT_b = i·Kb·m"},
    {title: "Depression in Freezing Point", tags: "Chemistry > Solutions", text: "ΔT_f = i·Kf·m"},
    {title: "Osmotic Pressure", tags: "Chemistry > Solutions", text: "π = i·CRT"},
    {title: "Van't Hoff Factor", tags: "Chemistry > Solutions", text: "i = Observed Property / Normal Property"},
    {title: "Nernst Equation", tags: "Chemistry > Electro", text: "E_cell = E°_cell - (0.0591/n)logQ"},
    {title: "Standard EMF", tags: "Chemistry > Electro", text: "E°_cell = E°_cathode - E°_anode"},
    {title: "Faraday's 1st Law", tags: "Chemistry > Electro", text: "m = ZIt"},
    {title: "Faraday's 2nd Law", tags: "Chemistry > Electro", text: "m₁/E₁ = m₂/E₂"},
    {title: "Kohlrausch's Law", tags: "Chemistry > Electro", text: "Λ°_m = ν₊λ°₊ + ν₋λ°₋"},
    {title: "Rate of Reaction", tags: "Chemistry > Kinetics", text: "Rate = k[A]ˣ[B]ʸ"},
    {title: "Zero Order Half-Life", tags: "Chemistry > Kinetics", text: "t_½ = [A]₀ / 2k"},
    {title: "First Order Rate Eq", tags: "Chemistry > Kinetics", text: "k = (2.303/t) log([A]₀/[A])"},
    {title: "First Order Half-Life", tags: "Chemistry > Kinetics", text: "t_½ = 0.693 / k"},
    {title: "Arrhenius Equation", tags: "Chemistry > Kinetics", text: "k = A·e^(-Ea/RT)"},
    {title: "Effective Nuclear Charge", tags: "Chemistry > Periodic", text: "Z_eff = Z - σ"},
    {title: "Dipole Moment", tags: "Chemistry > Bonding", text: "μ = q × d"},
    {title: "Formal Charge", tags: "Chemistry > Bonding", text: "FC = V - N - (B/2)"},
    {title: "Bond Order (MOT)", tags: "Chemistry > Bonding", text: "BO = ½(N_b - N_a)"},
    {title: "EAN Rule", tags: "Chemistry > Coordination", text: "EAN = Z - ON + 2(CN)"},
    {title: "Crystal Field Stabilization Energy", tags: "Chemistry > Coordination", text: "CFSE = (-0.4t₂g + 0.6eg)Δ₀"},
    {title: "Spin Only Magnetic Moment", tags: "Chemistry > Coordination", text: "μ = √(n(n+2)) BM"},
    {title: "Degree of Unsaturation", tags: "Chemistry > Organic", text: "DU = C + 1 - H/2 - X/2 + N/2"},
    {title: "Optical Isomers (n chiral centers)", tags: "Chemistry > Organic", text: "Max Stereoisomers = 2ⁿ"},
    {title: "Markovnikov's Rule", tags: "Chemistry > Organic", text: "H⁺ adds to C with more H's"},
    {title: "Zaitsev's Rule", tags: "Chemistry > Organic", text: "More substituted alkene is major"},
    {title: "Wurtz Reaction", tags: "Chemistry > Organic", text: "2RX + 2Na → R-R + 2NaX"},
    {title: "Friedel-Crafts Alkylation", tags: "Chemistry > Organic", text: "ArH + RX (AlCl₃) → ArR + HX"},
    {title: "Lucas Test Reagent", tags: "Chemistry > Organic", text: "Anhydrous ZnCl₂ + Conc. HCl"},
    {title: "Tollens' Reagent", tags: "Chemistry > Organic", text: "Ammoniacal AgNO₃"},
    {title: "Fehling's Solution A", tags: "Chemistry > Organic", text: "Aqueous CuSO₄"},
    {title: "Fehling's Solution B", tags: "Chemistry > Organic", text: "Rochelle salt + NaOH"},
    {title: "Cannizzaro Reaction Condition", tags: "Chemistry > Organic", text: "Aldehydes with ZERO α-H"},
    {title: "Aldol Condensation Condition", tags: "Chemistry > Organic", text: "Aldehydes/Ketones with ≥1 α-H"},
    {title: "Iodoform Test Reagent", tags: "Chemistry > Organic", text: "I₂ + NaOH"},
    {title: "Hofmann Bromamide", tags: "Chemistry > Organic", text: "R-CONH₂ + Br₂ + 4NaOH → R-NH₂"},
    {title: "Carbylamine Test", tags: "Chemistry > Organic", text: "R-NH₂ + CHCl₃ + 3KOH → R-NC"},
    {title: "Hinsberg's Reagent", tags: "Chemistry > Organic", text: "Benzene sulfonyl chloride"},
    {title: "Sandmeyer Reaction", tags: "Chemistry > Organic", text: "ArN₂⁺X⁻ + CuCl/HCl → ArCl"},
    {title: "Grignard Reagent", tags: "Chemistry > Organic", text: "R-Mg-X"},
    {title: "Saponification", tags: "Chemistry > Organic", text: "Ester + NaOH → Alcohol + Soap"},
    {title: "Esterification", tags: "Chemistry > Organic", text: "Acid + Alcohol (H⁺) ⇌ Ester + H₂O"},
    {title: "Rosenmund Reduction", tags: "Chemistry > Organic", text: "RCOCl + H₂ (Pd/BaSO₄) → RCHO"},
    {title: "Clemmensen Reduction", tags: "Chemistry > Organic", text: "C=O + Zn-Hg/HCl → CH₂"},
    {title: "Wolff-Kishner Reduction", tags: "Chemistry > Organic", text: "C=O + NH₂NH₂/KOH → CH₂"},
    {title: "Ozonolysis", tags: "Chemistry > Organic", text: "Alkene + O₃/Zn-H₂O → 2 Carbonyls"},
    {title: "Hydroboration-Oxidation", tags: "Chemistry > Organic", text: "Alkene + B₂H₆/H₂O₂ → Anti-Mark Alcohol"},
    {title: "Oxymercuration-Demercuration", tags: "Chemistry > Organic", text: "Alkene → Mark Alcohol (No rearrangement)"},
    {title: "Lindlar's Catalyst", tags: "Chemistry > Organic", text: "Alkyne + H₂ (Pd/CaCO₃) → Cis-Alkene"},
    {title: "Birch Reduction", tags: "Chemistry > Organic", text: "Alkyne + Na/Liq NH₃ → Trans-Alkene"},
    {title: "Victor Meyer Test", tags: "Chemistry > Organic", text: "Distinguishes 1°, 2°, 3° Alcohols"},
    {title: "Glucose Structure", tags: "Chemistry > Biomolecules", text: "Aldohexose (C₆H₁₂O₆)"},
    {title: "Fructose Structure", tags: "Chemistry > Biomolecules", text: "Ketohexose (C₆H₁₂O₆)"},
    {title: "Peptide Bond", tags: "Chemistry > Biomolecules", text: "-CO-NH- linkage"},
    {title: "DNA Nitrogenous Bases", tags: "Chemistry > Biomolecules", text: "Adenine, Thymine, Guanine, Cytosine"},
    {title: "RNA Specific Base", tags: "Chemistry > Biomolecules", text: "Uracil (replaces Thymine)"},
    {title: "Isoelectric Point", tags: "Chemistry > Biomolecules", text: "pH where amino acid has net zero charge"},
    {title: "Zwitterion", tags: "Chemistry > Biomolecules", text: "Dipolar ion of amino acid"},

    // ==========================================
    // MATHEMATICS (100 Formulas)
    // ==========================================
    {title: "Roots of Quadratic", tags: "Math > Algebra", text: "x = (-b ± √(b² - 4ac)) / 2a"},
    {title: "Sum of Roots", tags: "Math > Algebra", text: "α + β = -b / a"},
    {title: "Product of Roots", tags: "Math > Algebra", text: "αβ = c / a"},
    {title: "Discriminant", tags: "Math > Algebra", text: "Δ = b² - 4ac"},
    {title: "Nth Term of AP", tags: "Math > Progression", text: "T_n = a + (n-1)d"},
    {title: "Sum of n Terms of AP", tags: "Math > Progression", text: "S_n = (n/2)[2a + (n-1)d]"},
    {title: "Nth Term of GP", tags: "Math > Progression", text: "T_n = a·r^(n-1)"},
    {title: "Sum of n Terms of GP", tags: "Math > Progression", text: "S_n = a(r^n - 1) / (r - 1)"},
    {title: "Sum of Infinite GP", tags: "Math > Progression", text: "S_∞ = a / (1 - r)"},
    {title: "AM-GM Inequality", tags: "Math > Progression", text: "AM ≥ GM ≥ HM"},
    {title: "Logarithmic Product Rule", tags: "Math > Algebra", text: "log(xy) = log(x) + log(y)"},
    {title: "Logarithmic Power Rule", tags: "Math > Algebra", text: "log(x^y) = y·log(x)"},
    {title: "Base Change Formula", tags: "Math > Algebra", text: "log_b(a) = log_c(a) / log_c(b)"},
    {title: "Permutations", tags: "Math > P&C", text: "nPr = n! / (n-r)!"},
    {title: "Combinations", tags: "Math > P&C", text: "nCr = n! / [r!(n-r)!]"},
    {title: "Binomial Expansion", tags: "Math > Algebra", text: "(x+y)^n = Σ(nCr · x^(n-r) · y^r)"},
    {title: "General Term Binomial", tags: "Math > Algebra", text: "T_(r+1) = nCr · x^(n-r) · y^r"},
    {title: "Complex Number Modulus", tags: "Math > Complex", text: "|z| = √(a² + b²)"},
    {title: "Euler's Formula", tags: "Math > Complex", text: "e^(iθ) = cosθ + i·sinθ"},
    {title: "De Moivre's Theorem", tags: "Math > Complex", text: "(cosθ + i·sinθ)^n = cos(nθ) + i·sin(nθ)"},
    {title: "Cube Roots of Unity", tags: "Math > Complex", text: "1 + ω + ω² = 0"},
    {title: "Determinant 2x2", tags: "Math > Matrices", text: "|A| = ad - bc"},
    {title: "Inverse of Matrix", tags: "Math > Matrices", text: "A⁻¹ = (1/|A|) · adj(A)"},
    {title: "Cramer's Rule", tags: "Math > Matrices", text: "x = D₁/D, y = D₂/D, z = D₃/D"},
    {title: "Probability of Event", tags: "Math > Probability", text: "P(E) = n(E) / n(S)"},
    {title: "Addition Theorem", tags: "Math > Probability", text: "P(A∪B) = P(A) + P(B) - P(A∩B)"},
    {title: "Conditional Probability", tags: "Math > Probability", text: "P(A|B) = P(A∩B) / P(B)"},
    {title: "Bayes' Theorem", tags: "Math > Probability", text: "P(A_i|B) = P(B|A_i)P(A_i) / ΣP(B|A_j)P(A_j)"},
    {title: "Binomial Distribution", tags: "Math > Probability", text: "P(X=r) = nCr · p^r · q^(n-r)"},
    {title: "Distance Formula", tags: "Math > Coordinate", text: "d = √[(x₂-x₁)² + (y₂-y₁)²]"},
    {title: "Section Formula", tags: "Math > Coordinate", text: "x = (mx₂ + nx₁) / (m + n)"},
    {title: "Area of Triangle", tags: "Math > Coordinate", text: "A = ½|x₁(y₂-y₃) + x₂(y₃-y₁) + x₃(y₁-y₂)|"},
    {title: "Slope of Line", tags: "Math > Coordinate", text: "m = tanθ = (y₂ - y₁) / (x₂ - x₁)"},
    {title: "Point-Slope Form", tags: "Math > Coordinate", text: "y - y₁ = m(x - x₁)"},
    {title: "Slope-Intercept Form", tags: "Math > Coordinate", text: "y = mx + c"},
    {title: "Distance of Point to Line", tags: "Math > Coordinate", text: "d = |ax₁ + by₁ + c| / √(a² + b²)"},
    {title: "Equation of Circle", tags: "Math > Conics", text: "(x-h)² + (y-k)² = r²"},
    {title: "General Eq of Circle", tags: "Math > Conics", text: "x² + y² + 2gx + 2fy + c = 0"},
    {title: "Radius of General Circle", tags: "Math > Conics", text: "r = √(g² + f² - c)"},
    {title: "Standard Parabola", tags: "Math > Conics", text: "y² = 4ax"},
    {title: "Focus of Parabola", tags: "Math > Conics", text: "(a, 0)"},
    {title: "Latus Rectum Parabola", tags: "Math > Conics", text: "Length = 4a"},
    {title: "Standard Ellipse", tags: "Math > Conics", text: "x²/a² + y²/b² = 1"},
    {title: "Eccentricity Ellipse", tags: "Math > Conics", text: "e = √(1 - b²/a²)"},
    {title: "Standard Hyperbola", tags: "Math > Conics", text: "x²/a² - y²/b² = 1"},
    {title: "Eccentricity Hyperbola", tags: "Math > Conics", text: "e = √(1 + b²/a²)"},
    {title: "Trig Identity 1", tags: "Math > Trig", text: "sin²θ + cos²θ = 1"},
    {title: "Trig Identity 2", tags: "Math > Trig", text: "sec²θ - tan²θ = 1"},
    {title: "Trig Identity 3", tags: "Math > Trig", text: "csc²θ - cot²θ = 1"},
    {title: "Sine of A+B", tags: "Math > Trig", text: "sin(A+B) = sinA·cosB + cosA·sinB"},
    {title: "Cosine of A+B", tags: "Math > Trig", text: "cos(A+B) = cosA·cosB - sinA·sinB"},
    {title: "Tangent of A+B", tags: "Math > Trig", text: "tan(A+B) = (tanA + tanB) / (1 - tanA·tanB)"},
    {title: "Double Angle Sine", tags: "Math > Trig", text: "sin(2θ) = 2sinθ·cosθ"},
    {title: "Double Angle Cosine", tags: "Math > Trig", text: "cos(2θ) = cos²θ - sin²θ"},
    {title: "Sine Rule", tags: "Math > Trig", text: "a/sinA = b/sinB = c/sinC = 2R"},
    {title: "Cosine Rule", tags: "Math > Trig", text: "cosA = (b² + c² - a²) / 2bc"},
    {title: "Standard Limit Sine", tags: "Math > Limits", text: "lim(x→0) sin(x)/x = 1"},
    {title: "Standard Limit Tan", tags: "Math > Limits", text: "lim(x→0) tan(x)/x = 1"},
    {title: "Standard Limit Exp", tags: "Math > Limits", text: "lim(x→0) (eˣ - 1)/x = 1"},
    {title: "Standard Limit Log", tags: "Math > Limits", text: "lim(x→0) ln(1+x)/x = 1"},
    {title: "Derivative of Power", tags: "Math > Calculus", text: "d/dx(xⁿ) = n·xⁿ⁻¹"},
    {title: "Derivative Product Rule", tags: "Math > Calculus", text: "(uv)' = u'v + uv'"},
    {title: "Derivative Quotient Rule", tags: "Math > Calculus", text: "(u/v)' = (u'v - uv') / v²"},
    {title: "Chain Rule", tags: "Math > Calculus", text: "dy/dx = (dy/du) · (du/dx)"},
    {title: "Derivative of sin", tags: "Math > Calculus", text: "d/dx(sinx) = cosx"},
    {title: "Derivative of cos", tags: "Math > Calculus", text: "d/dx(cosx) = -sinx"},
    {title: "Derivative of tan", tags: "Math > Calculus", text: "d/dx(tanx) = sec²x"},
    {title: "Derivative of e^x", tags: "Math > Calculus", text: "d/dx(eˣ) = eˣ"},
    {title: "Derivative of ln(x)", tags: "Math > Calculus", text: "d/dx(lnx) = 1/x"},
    {title: "Equation of Tangent", tags: "Math > AOD", text: "y - y₁ = (dy/dx)(x - x₁)"},
    {title: "Equation of Normal", tags: "Math > AOD", text: "y - y₁ = (-1 / (dy/dx))(x - x₁)"},
    {title: "Maxima & Minima Test", tags: "Math > AOD", text: "dy/dx = 0, then check d²y/dx²"},
    {title: "Integration Power Rule", tags: "Math > Calculus", text: "∫ xⁿ dx = (xⁿ⁺¹)/(n+1) + C"},
    {title: "Integration of 1/x", tags: "Math > Calculus", text: "∫ 1/x dx = ln|x| + C"},
    {title: "Integration of sin", tags: "Math > Calculus", text: "∫ sinx dx = -cosx + C"},
    {title: "Integration of cos", tags: "Math > Calculus", text: "∫ cosx dx = sinx + C"},
    {title: "Integration by Parts", tags: "Math > Calculus", text: "∫ u v dx = u∫v dx - ∫(u'∫v dx)dx"},
    {title: "Definite Integral Property", tags: "Math > Calculus", text: "∫(a to b) f(x)dx = ∫(a to b) f(a+b-x)dx"},
    {title: "Area Under Curve", tags: "Math > Calculus", text: "A = ∫ |y| dx"},
    {title: "Linear Diff Equation", tags: "Math > DiffEq", text: "dy/dx + Py = Q"},
    {title: "Integrating Factor (IF)", tags: "Math > DiffEq", text: "IF = e^(∫P dx)"},
    {title: "Vector Dot Product", tags: "Math > Vectors", text: "A·B = |A||B|cosθ"},
    {title: "Vector Cross Product", tags: "Math > Vectors", text: "|A×B| = |A||B|sinθ"},
    {title: "Unit Vector", tags: "Math > Vectors", text: "â = A / |A|"},
    {title: "Direction Cosines", tags: "Math > 3D Geo", text: "l² + m² + n² = 1"},
    {title: "Angle Between Lines", tags: "Math > 3D Geo", text: "cosθ = l₁l₂ + m₁m₂ + n₁n₂"},
    {title: "Equation of Plane", tags: "Math > 3D Geo", text: "ax + by + cz + d = 0"},
    {title: "Distance Point to Plane", tags: "Math > 3D Geo", text: "d = |ax₁ + by₁ + cz₁ + d| / √(a²+b²+c²)"},
    {title: "Shortest Dist Skew Lines", tags: "Math > 3D Geo", text: "d = |(a₂-a₁)·(b₁×b₂)| / |b₁×b₂|"},
    {title: "Variance", tags: "Math > Statistics", text: "σ² = (Σ(x_i - μ)²) / N"},
    {title: "Standard Deviation", tags: "Math > Statistics", text: "σ = √Variance"}
];

const resultsDiv = document.getElementById("results");
const searchInput = document.getElementById("searchInput");
const folderBtns = document.querySelectorAll('.folder-btn');

let currentSubject = "All"; 

function displayFormulas(formulas) {
    resultsDiv.innerHTML = ""; 
    if (formulas.length === 0) {
        resultsDiv.innerHTML = "<p style='grid-column: 1/-1; text-align: center; color: #a1a1aa;'>No formulas found.</p>";
        return;
    }
    formulas.forEach(item => {
        resultsDiv.innerHTML += `
            <div class="card">
                <div class="tag">${item.tags}</div>
                <h3>${item.title}</h3>
                <div class="formula">${item.text}</div>
            </div>
        `;
    });
}

function filterFormulas() {
    const query = searchInput.value.toLowerCase().trim();
    const filtered = database.filter(item => {
        const matchesSearch = item.title.toLowerCase().includes(query) || item.tags.toLowerCase().includes(query) || item.text.toLowerCase().includes(query);
        const matchesSubject = currentSubject === "All" || item.tags.includes(currentSubject);
        return matchesSearch && matchesSubject;
    });
    displayFormulas(filtered);
}

folderBtns.forEach(btn => {
    btn.addEventListener('click', () => {
        folderBtns.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        currentSubject = btn.getAttribute('data-subject');
        filterFormulas();
    });
});

searchInput.addEventListener("input", filterFormulas);
displayFormulas(database);